### PR TITLE
Add device binding for Pimoroni Blinkt!.

### PR DESCRIPTION
**Pull request by devinh**
Binding for the [Pimoroni Blinkt!](https://github.com/pimoroni/blinkt) 8 LED strip.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/iot?pullRequest=1171) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/iot?pullRequest=1171) before we can accept your contribution.<br/><br/>:x: devinh [sign now](https://cla.dotnetfoundation.org/dotnet/iot?pullRequest=1171)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/iot?pullRequest=1171) it.</sub>

**Comment by HumJ0218** [comment]
I wonder if this PR maybe duplicate with #1098 because Blinkt! is a 8-APA102 LED strip.
@krwq

**Comment by devinh** [comment]
> 
> 
> I wonder if this PR duplicate with #1098 because Blinkt! is a 8-APA102 LED strip.
> @krwq

They're related in that the Blinkt uses 8 APA102's but that's it. The Blinkt talks on GPIO pins 23 & 24. Where as the APA102 is via one of the standard SPI interfaces.

**Comment by HumJ0218** [comment]
dotnet/iot also provides software SPI implementations. [SoftwareSpi](/dotnet/iot/tree/master/src/devices/SoftwareSpi)

PS. This module is quite interesting.

**Comment by dhowardimpinj** [comment]
> 
> 
> dotnet/iot also provides software SPI implementations. [SoftwareSpi](/dotnet/iot/tree/master/src/devices/SoftwareSpi)
> 
> PS. This module is quite interesting.

Hmm, okay I'll look into using this.

**Comment by devinh** [comment]
> 
> 
> dotnet/iot also provides software SPI implementations. [SoftwareSpi](/dotnet/iot/tree/master/src/devices/SoftwareSpi)
> 
> PS. This module is quite interesting.

Hmm, okay I'll look into using this.

**Comment by devinh** [comment]
So after some sleuthing this evening working with the SoftwareSpi and looking closer into the Apa102 library. The Apa102 with the  SoftwareSpi works sufficiently with the Blinkt. As such I'll rescind this PR.

**Pull request closed without merging**
