### PR TITLE
Ccs811 orthograph adjustment

### PR DESCRIPTION
**Pull request by Ellerbach**
- Fix orthograph issue in PR #1151 Volatil -> Volatile

### CODE REVIEW

**Comment by danmosemsft** [comment]
Thanks. @richlander and I were chatting, he mentioned that it might be good soon to do an all-up pass through the API for consistent naming etc, and a review of the public abstractions.

**Comment by krwq** [comment]
@danmosemsft makes sense, for now we have been doing sweep passes whenever we have identified something specific. For System.Device.Gpio we are much more careful with naming to make sure we don't introduce any breaking changes. For Iot.Device.Bindings (like i.e. this binding) we have been allowing some breaking changes if they were justified but we've tried to avoid them as much as possible (also depending on how commonly given API is used).

**Comment by krwq** [comment]
unrelated failures again

**Comment by Ellerbach** [comment]
> Thanks. @richlander and I were chatting, he mentioned that it might be good soon to do an all-up pass through the API for consistent naming etc, and a review of the public abstractions.

And maybe good as well to give clear naming recommendations for the function variables and naming as well. You get the experience thru PR. Maybe good to have couple of example like do/don't somewhere. I4ll think of it and will propose something.

**Pull request merged**
