### PR TITLE
Adding Retry helper to InputPullResistorsWork test since it may fail sometimes

### PR DESCRIPTION
**Pull request by joperezr**
cc: @krwq @pgrawehr 

Contributes to #941 

This will try to mitigate CI failures by adding 5 retries in case this test fails until it ultimately fails the test and throws.

### CODE REVIEW

**Comment by joperezr** [comment]
@pgrawehr One more strategy we could do here is to add more logging in order to try to understand what went wrong.

**Comment by pgrawehr** [comment]
Yea, I've seen this test fail sometimes on my board, too. Since it _is_ flaky, I haven't figured out what fixes it. I first thought of introducing sleeps after changing the pull mode, but that didn't seem to be enough at times. I will try again.

**Comment by krwq** [comment]
I'm fine with adding retries but do we have any idea what is causing the retries to be needed? Can we open issues about this along with this fix? Until we have full understanding why is this happening I'd prefer we kept the issue open.

I'd expect this scenario to work reliably to be honest and not sure why this is failing.

**Comment by joperezr** [comment]
Logged #943 to track that.

**Pull request merged**
