### PR TITLE
Update file-scoped namespaces and unused usings

### PR DESCRIPTION
**Pull request by shaggygi**
Cleaned up a few areas in main GPIO and test projects.
- Updated to C# 10.
- Updated to file-scoped namespaces.
- Removed unused usings.

**NOTE**: This might appear to be a large update, but mainly because of the namespace format changes.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/iot/pull/1881)

### CODE REVIEW

**Comment by joperezr** [comment]
Good to hear from you @shaggygi, thanks for the PR, I will take a look at it very soon but at least looks great with a quick initial skim. Thanks for modernizing the repo. I will prioritize this PR due to obvious reasons, as it spans many files and we don't want to cause merge conflicts.

Question: did you use a specific analyzer (or analyzers) to make these changes?

**Review by joperezr — APPROVED** [review]
Thanks @shaggygi

**Comment by shaggygi** [comment]
@joperezr good to hear from you, as well.  I had some downtime and was looking over the repo.  I used the unused using analyzer, but manually did the file-scoped namespaces.  I can't find where I read it, but there is supposed to be one in the works.  I hope so as that would be a huge time savings.  😄

**Comment by joperezr** [comment]
I mainly asked because it would be good to do this repo-wide. Even if there is no analyzer for this, looks like it should be easy enough to write one.

**Comment by shaggygi** [comment]
Yeah, but not sure about projects that are not set to 10, preview, or latest.  Not sure if it would pick those up or not.

**Comment by shaggygi** [comment]
Well, look what was released in VS17P3 today.  I'll give it a try on the binding projects this weekend.

image

**Pull request merged**
