### PR TITLE
Make System.Device.Gpio work on Mono

### PR DESCRIPTION
**Pull request by krwq**
Fixes https://github.com/dotnet/iot/issues/1089

Use workaround provided by Mono for the type loading issue.

cc: @Ellerbach

### CODE REVIEW

**Comment by krwq** [comment]
@joperezr yes, I've tried if calling SpiDevice.Create/I2cDevice.Create/new GpioGontroller/PwmChannel.Create doesn't cause any TypeLoadException.

**Comment by Ellerbach** [comment]
Thanks a lot @krwq for fixing the issue! This new version works like a charm with mono on my Raspberry Pi Zero.

**Comment by R10Rasmus** [comment]
I still have problems with System.Device.Gpio on mono (running on my Raspberry Pi Zero). 
I use version 1.1.0-prerelease.20153.1 of System.Device.Gpio. 
I get this error:
Unhandled Exception:
System.PlatformNotSupportedException: Operation is not supported on this platform.
  at diod.Program.Main (System.String[] args) [0x0000c] in <807d9bdced0d4b01bab17bb49da4e5d9>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.PlatformNotSupportedException: Operation is not supported on this platform.
  at diod.Program.Main (System.String[] args) [0x0000c] in <807d9bdced0d4b01bab17bb49da4e5d9>:0

hope you can help :)

**Comment by Ellerbach** [comment]
@R10Rasmus, just a stupid question: are you running a .NET Framework 4.8 application on the Pi Zero? .NET Core application are not supported. 
The fix provided solved my problem and it's perfectly working with a .NET Framework 4.8 application.

**Comment by R10Rasmus** [comment]
@Ellerbach I did run a .Net Core version. I is now convert to an .NET Framework 4.8 application, but I get the same issue. 
I am running it like this:

mono diode.exe
Hello World!

Unhandled Exception:
System.PlatformNotSupportedException: Operation is not supported on this platform.
  at diode.Program.Main (System.String[] args) [0x0000c] in <00d189148f054da3a840744526508385>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.PlatformNotSupportedException: Operation is not supported on this platform.
  at diode.Program.Main (System.String[] args) [0x0000c] in <00d189148f054da3a840744526508385>:0

**Comment by Ellerbach** [comment]
@R10Rasmus , try from https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json one of the latest version like 1.1.0-prerelease.20276.1

**Comment by R10Rasmus** [comment]
@Ellerbach I use version 1.1.0-prerelease.20153.1. If I try to install 1.1.0-prerelease.20276.1 from https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json I gen an dependency error:

Attempting to gather dependency information for package 'System.Device.Gpio.1.1.0-prerelease.20276.1' with respect to project 'C:\Users\rasmu\source\repos\pi\diod', targeting 'Any,Version=v0.0'
Gathering dependency information took 6,63 sec
Attempting to resolve dependencies for package 'System.Device.Gpio.1.1.0-prerelease.20276.1' with DependencyBehavior 'Lowest'
nuget : Unable to resolve dependency 'System.Memory'. Source(s) used: 'nuget.org', 'Gpio'.
At line:1 char:1
+ nuget install System.Device.Gpio -PreRelease -Source https://pkgs.dev ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to resol...t.org', 'Gpio'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

I still get this error, if I install System.Memory from nuget.org :(

**Comment by R10Rasmus** [comment]
@Ellerbach I got it to work :) 
I build System.Device.Gpio my self from master and then I installed libgpiod-dev on my Pi Zero.

**Comment by Ellerbach** [comment]
> I got it to work :)

Great! Yes, libgpiod-dev is needed in the Pi Zero. I have a service running for the last few weeks like a charm. Few things to keep in mind: you you want to manage gpio pin state changes, it's not working the best. If you have only 1 thread, then the events are coming in. If you start to have a large app with a lot of thread, then for some reason, you'll stop getting the events. So in this case, just do a thread dedicated to the pin change.

**Pull request merged**
