### PR TITLE
Adds a driver to perform software simulations

### PR DESCRIPTION
**Pull request by mcNets**
Hi, it's the first time I create a PR in a public repository and I hope I've done it correctly. 

I've added a new driver that allows to perform software simulations without any connected device. It is useful, at least to me, because you can develop the main application in your computer and later move it to the device.

By default I used the same numbering schema of the Raspberry Pi, that is the device I'm working with. Of course you must add a piece of code to activate/deactivate the IO signals, but that code can be removed or commented later before to use it in the final device.

This driver allows to read/write both signals input and output and if needed, your can pass your own NumberToLogicalConverter function to the constructor in addition to the maximum number of pins.

I have some samples in my personal repository: [mcNets/Gpio.Driver.Simulator](https://github.com/mcNets/Gpio.Driver.Simulator), I think that [Sample.WPF.Simulation1](https://github.com/mcNets/Gpio.Driver.Simulator/tree/master/Sample.WPF.Simulation1) is a good example on how this driver can be used.

If it is accepted, I could remove my repository and add the samples to this one with the corresponding tests.

Regards.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/iot/pull/1827)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/iot?pullRequest=1827) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/iot?pullRequest=1827) before we can accept your contribution.<br/><br/>:x: mcNets [sign now](https://cla.dotnetfoundation.org/dotnet/iot?pullRequest=1827)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/iot?pullRequest=1827) it.</sub>

**Comment by pgrawehr** [comment]
PR #1823 is suggesting a similar approach. We have discussed this briefly in last weeks triage call, and we generally agreed that we did want something like that, but it should probably be more generic than this. I'll write up an issue with proposed requirements for a simulation API tomorrow.

@mcNets Thanks for your proposal, but I think before I start reviewing your code, we should be clear about the requirements in this case.

**Comment by mcNets** [comment]
> PR #1823 is suggesting a similar approach. We have discussed this briefly in last weeks triage call, and we generally agreed that we did want something like that, but it should probably be more generic than this. I'll write up an issue with proposed requirements for a simulation API tomorrow.
> 
> @mcNets Thanks for your proposal, but I think before I start reviewing your code, we should be clear about the requirements in this case.

It's fine. I subscribed to PR #1823 to follow up on this topic. Thanks @pgrawehr

**Comment by krwq** [comment]
[Triage] Let's make sure this doesn't collide with https://github.com/dotnet/iot/pull/1823

**Comment by pgrawehr** [comment]
[Triage] Before we can continue on this one, a design discussion (#1828) is required, as this needs a bit more background than what we have now. If there's no further update, we'll close this for now, until someone finds time to provide an extended design (eventually with a prototype).

**Pull request closed without merging**
