### PR TITLE
A GPIO has to be writeable even in drive mode input

### PR DESCRIPTION
**Pull request by mstroppel**
...because one wants to set the value used when switching to output mode.

Detailed explanation:

CPU's GPIO pins are set to input mode upon system start. Via pull-up or pull-down resistor the state can be determined on schematic/electronic side.
If the pin is used as an output, the software can set the mode to output. But before it has to be possible to set the output state to ensure that the output state is where it should be upon switching from input to output state.

A simplified schematic of GPIO internals:

```text
                           Vcc
                          /
                   ------X2 high / low switch
                  /       \
                 /         GND
                /
GPIO pin ------ X1 input / output switch or output activate switch (input will still be there)
                \
                 ------- Input logic
```

So before switching X1 we should define in which state X2 is.

I had the case with an Apollo Lake CPU where:

```csharp
_gpioController.SetDriveMode(1, PinMode.Output)
_gpioController.Write(1, PinValue.Low)
```
Lead to a short high peak in the output that I have to avoid. That's why I had to switch to use `Windows.Devices.Gpio` via the NuGet `Microsoft.Windows.SDK.Contracts`, which allows to write before setting to output.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/iot?pullRequest=1361) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/iot?pullRequest=1361) before we can accept your contribution.<br/><br/>:x: mstroppel [sign now](https://cla.dotnetfoundation.org/dotnet/iot?pullRequest=1361)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/iot?pullRequest=1361) it.</sub>

**Comment by pgrawehr** [comment]
I've seen the same behavior on other hardware as well, so I think the proposed change is a good idea.

**Comment by mstroppel** [comment]
Guys, as far as I can see, the failing build is not my fault. Did someone cut the connection between the input and output pin?

**Comment by krwq** [comment]
Seems like SysFs implementation doesn't like this new capability:

```
    System.Device.Gpio.Tests.SysFsDriverTests.AllowWritingOnInputPin [FAIL]
      System.UnauthorizedAccessException : Reading a pin value requires root permissions.
      ---- System.UnauthorizedAccessException : Access to the path '/sys/class/gpio/gpio6/value' is denied.
      -------- System.IO.IOException : Operation not permitted
```

ddvsorpil022 might have some hardware issues though

**Comment by pgrawehr** [comment]
If sysfs really doesn't like this feature, we could also just move the exception to the driver. I think we shouldn't prevent this for all drivers if only one of them fails to support it, since sysfs is mostly deprecated, anyway.

**Comment by krwq** [comment]
@pgrawehr seems they now recommend to use chardev devices: https://www.kernel.org/doc/Documentation/gpio/consumer.txt instead

**Comment by krwq** [comment]
@joperezr @Ellerbach are you ok with SysFs throwing NotSupportedException while other GPIO drivers would allow for this scenario?

**Comment by pgrawehr** [comment]
Alternatively, we could also have sysfs emulate this (by storing the desired value). It wouldn't fix the original issue when using sysfs, but the behavior would be otherwise the same.

**Comment by krwq** [comment]
or change mode, write value, and change mode back (not sure if that would work though)

**Comment by microhobby** [comment]
Well, this will not have any side effects in `LibGpioDriver` but otherwise, it will be useless. Once configured the pin handle is locked. If there is an attempt to change the `PinMode` we will have an `EBUSY` exception. The only way to switch to another `PinMode` is to call `ClosePin` first, which will lose the previously written status anyway.

For `LibGpioDriver` we must add an API to call the `int gpiod_line_set_direction_output(struct gpiod_line *line, int value)` that enables to drive the pin to output with a default value.

Or maybe add the:

```csharp
OpenPin(int pinNumber, PinMode mode, PinValue initialValue);
SetPinMode(int pinNumber, PinMode mode, PinValue initialValue);
```

**Comment by pgrawehr** [comment]
@microhobby Are you saying that with the libgpiodriver, it is already not possible to use SetPinMode to change from input to output or vice-versa? So the existing implementation would throw an exception when trying to do so?

**Comment by microhobby** [comment]
> @microhobby Are you saying that with the libgpiodriver, it is already not possible to use SetPinMode to change from input to output or vice-versa? So the existing implementation would throw an exception when trying to do so?

@pgrawehr yes, I wrote an attempt to evaluate it and:

9zS6ZOJH8L

**Comment by pgrawehr** [comment]
Bad... I suppose we should fix that with a workaround. There are some sensors (i.e. DHT11) that require quick switching of single lines from input to output and back.

**Comment by Ellerbach** [comment]
@krwq and @pgrawehr I would prefer to implement something even slower on SysFs than raising a not implemented exception. The reason is just because if someone will want to use this and doesn't really have the knowledge, they would not understand the issue. Now, I understand it's an advance scenario, still.

**Comment by joperezr** [comment]
[Triage]: Closing this PR as it is now superseded by https://github.com/dotnet/iot/pull/1473. Commits from here have been cherry-picked.

**Pull request closed without merging**
