### PR TITLE
Update for March servicing

### PR DESCRIPTION
**Pull request by richlander**
Happy Pi day!

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/iot/pull/2050)

### CODE REVIEW

**Comment by joperezr** [comment]
Seems like the Button.Tests unit tests (cc: @raffaeler ) are failing on this PR, but not sure if they are just flaky or something here is affecting it which I doubt. I'll re-run to double-check.

**Comment by raffaeler** [comment]
@joperezr I opened all the logs but I only see:
- `Platform 'esp32:esp32' not found: platform not installed`
- `##[error]Artifact BuildPackages already exists for build 89568.`

Could you please give me the link to the failed test?

**Comment by joperezr** [comment]
Yeah, this is because if the unit test project that fails doesn't have the UI thread it won't log the errors because the runner has had a bug for a long time where it uses `Console.WriteLine` as opposed to `Log.WriteLine` which means that in a multi-threaded build, you would likely miss the errors getting printed. Seems like this is failing consistently on Windows, we should try to pull the changes on this branch locally and run those tests and we should be able to repro

**Comment by raffaeler** [comment]
Got it, but where did you see the button tests failing?
Can you tell me at least which one was failing?

**Comment by joperezr** [comment]
Merging since the Arduino leg has now been disabled and therefore won't re-run.

**Pull request merged**
