### PR TITLE
Added markdown-link-check to azure-pipelines.yml

### PR DESCRIPTION
**Pull request by Jimmys20**
This PR adds `markdown-link-check` to `azure-pipelines.yml`. It is already added to `.vsts-ci.yml` as part of https://github.com/dotnet/iot/pull/1970.

Seems to be [working](https://dev.azure.com/dotnet/IoT/_build/results?buildId=82062&view=logs&j=fa59fe4e-195c-56fa-189b-58fd241f10dd&t=71146b80-38e1-5fea-9b74-ba1045aac3e1) now. I wonder if the script should be modified to allow it to continue scanning after a problematic link is found and maybe show warning instead of throwing. Sometimes links might be temporary down like in this case, [hackernoon.com is down](https://twitter.com/hackernoon/status/1587981429992046592?cxt=HHwWgIC-yc6s0oksAAAA) and the script stopped execution but it would be nice if it continued scanning.

Also `https://www.digikey.com/` got Status: 403 Forbidden which is interesting. Never had that happen while testing locally.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/iot/pull/1974)

### CODE REVIEW

**Comment by joperezr** [comment]
Hello @Jimmys20, thank you so much for the contribution. We discussed this PR during triage and decided that it was probably better if we had this step to run on its own job in order for it to be easier for us to diagnose the reason for a failing build. I hope you don't mind, but I took the liberty to push the appropriate changes into your PR in order to adjust for that.

**Review by joperezr — APPROVED** [review]

**Comment by Jimmys20** [comment]
Relevant [issue](https://github.com/tcort/markdown-link-check/issues/220) and [explanation](https://github.com/tcort/link-check/issues/47#issuecomment-847764254) why some links return 403 forbidden.

**Comment by joperezr** [comment]
@Jimmys20 would you mind also checking why we are now getting another failure? I'd rather add more patterns to skip but keep the check green before we merge.

**Comment by Jimmys20** [comment]
Looks like it's not very consistent with the external URLs. I committed a change (added verbose logging) which made the task rerun and now it stopped in a different URL. It is strange because all those links are reported as alive when I run the command on my computer.

mdlc

mdlc2

mdlc3

**Comment by krwq** [comment]
@Jimmys20 for links which you are 100% sure they are not going down anytime soon (Ali Express or digi key) you can just add them to the ignore list permanently

**Comment by Jimmys20** [comment]
`Execute markdown-link-check` job completed successfully.

**Comment by pgrawehr** [comment]
@krwq aliexpress isn't going down anytime soon, but the deep links within it (e.g. to a product) surely can.

**Comment by krwq** [comment]
@pgrawehr I know but the specific link shared was a root path :)

**Comment by krwq** [comment]
Thanks @Jimmys20!

**Pull request merged**
