### PR TITLE
WIP: GpioController: LibGpiodDriver: Add methods to handle pins by name

### PR DESCRIPTION
**Pull request by microhobby**
From Linux Kernel docs[1]:

> "Optionally, a GPIO controller may have a "gpio-line-names" property.
> This is an array of strings defining the names of the GPIO lines going
> out of the GPIO controller. This name should be the most meaningful
> producer name for the system, such as a rail name indicating the usage."

`gpiod_line_find` searches for a gpio line that was defined in
`gpio-line-names` and return its handle. This is very useful to avoid
having to search in the datasheets the pin bank/line. The user can
check the labels with the pin names on the PCB and use it instead.

1: https://www.kernel.org/doc/Documentation/devicetree/bindings/gpio/gpio.txt

Example:

The Toradex has a family of computer on modules that are pin compatible. But among the board models, we can have different SoCs. For example the [Apalis Family](https://www.toradex.com/computer-on-modules/apalis-arm-family):

Accesing the `MXM3_3/GPIO2` pin on a [Apalis iMX8QM](https://www.toradex.com/computer-on-modules/apalis-arm-family/nxp-imx-8):

image

Accessing the `MXM3_3/GPIO2` pin on [Apalis iMX6Q](https://www.toradex.com/pt-br/computer-on-modules/apalis-arm-family/nxp-freescale-imx-6):

image

The pin in the form factor (hardware) is the same for the two computer on modules but inside the SoC the gpio bank/line numbers changes because of course they are different (arm32v7 for iMX6 and arm64v8 for iMX8 and etc ...).

Using the  `gpio-line-names` the hardware vendor supply a BSP that is also pin-compatible at the software level.

With the changes proposed in this merge request we can write the follow:

```csharp
// Note that libgpiod bank number is not necessary this will be abstracted by the gpiod_line_find
GpioController gpioController = new GpioController();
gpioController.OpenPin("MXM3_3/GPIO2", PinMode.Output);
gpioController.Write("MXM3_3/GPIO2", PinValue.Low);
```

This will work on both Apalis iMX8 and iMX6, we can use a single code base that will work on all hardware compatible with a family of form factor that is compatible.
 
Raspberry Pi also define `gpio-line-names` on their BSP, the pins can also be accessed by their respective names: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm/boot/dts/bcm2837-rpi-3-b.dts#n61

### CODE REVIEW

**Comment by pgrawehr** [comment]
While I think it is a good idea to reduce platform-dependency as far as possible, I'm not sure we should add so much extra code for this to the core. What about just creating a simple module that does the translation? Is there a way to do a string->int transformation by querying some data from libgpiod? 

Additionally, your change breaks the existing tests, likely because the new methods are being used already. Snip of test log:
```
System.Device.Gpio.Tests.RaspberryPiDriverTests.PinValueReadAndWrite [FAIL]
      System.PlatformNotSupportedException : Open pin by name is supported only on Libgpiod driver
      Stack Trace:
        /_/src/System.Device.Gpio/System/Device/Gpio/GpioDriver.cs(51,0): at System.Device.Gpio.GpioDriver.ClosePin(String pinName)
        /_/src/System.Device.Gpio/System/Device/Gpio/GpioController.cs(199,0): at System.Device.Gpio.GpioController.ClosePinCore(String pinName)
        /_/src/System.Device.Gpio/System/Device/Gpio/GpioController.cs(584,0): at System.Device.Gpio.GpioController.Dispose(Boolean disposing)
        /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(61,0): at System.Device.Gpio.Tests.GpioControllerTestBase.PinValueReadAndWrite()
    System.Device.Gpio.Tests.RaspberryPiDriverTests.PinValueReadAndWrite [FINISHED] Time: 0.0415625s
    System.Device.Gpio.Tests.RaspberryPiDriverTests.WaitForEventFallingEdgeTest [STARTING]
    System.Device.Gpio.Tests.RaspberryPiDriverTests.WaitForEventFallingEdgeTest [FAIL]
```

**Comment by microhobby** [comment]
> While I think it is a good idea to reduce platform-dependency as far as possible, I'm not sure we should add so much extra code for this to the core. What about just creating a simple module that does the translation? Is there a way to do a string->int transformation by querying some data from libgpiod?
> 

The problem is that it is not as out of the box as just using `OpenPin`, a translation would give us a pair of bank/line, and then we would have to instantiate a new driver to set the bank reference and then do the operations on the pin. Maybe it's a matter of improving the code here to try to reduce duplicate code and work with `SafeLineHandle` reference. 

The ideal would be a redesign of the API to work with a pin object that would have the bank/pin reference instead of just work with the number reference of the pin (something that was inherited from sysfs that doesn't make sense on libgpiod unless your hardware has only one gpio bank)

> Additionally, your change breaks the existing tests, likely because the new methods are being used already. Snip of test log:
> 
> ```
> System.Device.Gpio.Tests.RaspberryPiDriverTests.PinValueReadAndWrite [FAIL]
>       System.PlatformNotSupportedException : Open pin by name is supported only on Libgpiod driver
>       Stack Trace:
>         /_/src/System.Device.Gpio/System/Device/Gpio/GpioDriver.cs(51,0): at System.Device.Gpio.GpioDriver.ClosePin(String pinName)
>         /_/src/System.Device.Gpio/System/Device/Gpio/GpioController.cs(199,0): at System.Device.Gpio.GpioController.ClosePinCore(String pinName)
>         /_/src/System.Device.Gpio/System/Device/Gpio/GpioController.cs(584,0): at System.Device.Gpio.GpioController.Dispose(Boolean disposing)
>         /_/src/System.Device.Gpio.Tests/GpioControllerTestBase.cs(61,0): at System.Device.Gpio.Tests.GpioControllerTestBase.PinValueReadAndWrite()
>     System.Device.Gpio.Tests.RaspberryPiDriverTests.PinValueReadAndWrite [FINISHED] Time: 0.0415625s
>     System.Device.Gpio.Tests.RaspberryPiDriverTests.WaitForEventFallingEdgeTest [STARTING]
>     System.Device.Gpio.Tests.RaspberryPiDriverTests.WaitForEventFallingEdgeTest [FAIL]
> ```

Thanks for pointing it @pgrawehr I'm converting this to draft to check the tests. 

I would also like the opinion of @joperezr and @buyaa-n on this.
Thanks

**Comment by pgrawehr** [comment]
> The ideal would be a redesign of the API to work with a pin object that would have the bank/pin reference instead of just work with the number reference of the pin (something that was inherited from sysfs that doesn't make sense on libgpiod unless your hardware has only one gpio bank)

We're considering this, see #215. It's currently not top-prio, though.

**Comment by krwq** [comment]
If you put that directly on LibGpiodDriver and not on generic GpioController I'm fine with adding extra utilities. How would you see the APIs for this?

**Comment by buyaa-n** [comment]
This is a useful feature for LibGpiod driver but seems not supported for other drivers, i don't think we can add it without adding on generic GpioController. Not sure if we want to just throw for the other drivers when accessing string overload, probably just wait for https://github.com/dotnet/iot/issues/215 support added

**Comment by microhobby** [comment]
> This is a useful feature for LibGpiod driver but seems not supported for other drivers, i don't think we can add it without adding on generic GpioController. Not sure if we want to just throw for the other drivers when accessing string overload, probably just wait for #215 support added

Yes, totally agree. Unfortunately, I don't have the time to work on the #215 right now, and it has to be done calmly and think carefully. So, I'm thinking of just adding new methods to the `LibGpiodDriver` to handle this specific behavior:

```csharp
LibGpiodDriver gpioController = new LibGpiodDriver(6);
gpioController.OpenPinByName("MXM3_3/GPIO2", PinMode.Output);
gpioController.WriteByName("MXM3_3/GPIO2", PinValue.Low);
gpioController.ReadByName("MXM3_3/GPIO2");
gpioController.CloseByName("MXM3_3/GPIO2");
```

Summarizing, the idea is to have the controls methods with "ByName" to handle this.
@pgrawehr @krwq @buyaa-n @joperezr let me know what you guys think.

**Comment by microhobby** [comment]
> > This is a useful feature for LibGpiod driver but seems not supported for other drivers, i don't think we can add it without adding on generic GpioController. Not sure if we want to just throw for the other drivers when accessing string overload, probably just wait for #215 support added
> 
> Yes, totally agree. Unfortunately, I don't have the time to work on the #215 right now, and it has to be done calmly and think carefully. So, I'm thinking of just adding new methods to the `LibGpiodDriver` to handle this specific behavior:
> 
> ```cs
> LibGpiodDriver gpioController = new LibGpiodDriver(6);
> gpioController.OpenPinByName("MXM3_3/GPIO2", PinMode.Output);
> gpioController.WriteByName("MXM3_3/GPIO2", PinValue.Low);
> gpioController.ReadByName("MXM3_3/GPIO2");
> gpioController.CloseByName("MXM3_3/GPIO2");
> ```
> 
> Summarizing, the idea is to have the controls methods with "ByName" to handle this.
> @pgrawehr @krwq @buyaa-n @joperezr let me know what you guys think.

Ok, updating it. I forgot a important detail, we will need these on the generic controller right. @buyaa-n  I know it is boring to have this throwing `Not supported` to the others drivers but I think it is the easiest and shortest solution 🙄.

Another thing I thought would be to add maybe another Controller for Libgpiod:

```
// first argument the gpio bank
LibGpiodController controller = new LibGpiodController(6, PinNumberingScheme.Logical);
```

But I'm not sure if it would be worth it. Or maybe add it to the bindings, well, thinking out loud here ... 😁

**Comment by joperezr** [comment]
I wouldn't add an extra controller for libgpiod driver. I think that the way to go about it here would be to just add this functionality only the libgpiodriver, and to have to be called via the driver directly, similar to the way we have some registers exposed via the RaspberryPiDriver directly. Also, regarding the "ByName" suffix, I think that instead of that, a more adecuate solution would be to drop the suffix and instead just create new overloads that take in strings instead of ints to identify pins for that driver. Also, these methods that get implemented directly in the driver should do some of the validation that the controller does today before passing the calls to the driver as you would be skipping that layer. Basically this is more or less what I'm thinking:

```c#
LibGpiodDriver myDriver = new LibGpiodDriver(6);
GpioController myController = new GpioController(PinNumberingScheme.Logical, myDriver);

// When not using the byName overloads, you can just call the controller directly like before:
myController.Open(16, PinMode.Output);
myController.Write(16, PinValue.Low);
myController.Read(16);
myController.Close(16);

// When using the byName overloads, then call via the Driver directly:
myDriver.Open("MXM3_3/GPIO2", PinMode.Output);
myDriver.Write("MXM3_3/GPIO2", PinValue.Low);
myDriver.Read("MXM3_3/GPIO2");
myDriver.Close("MXM3_3/GPIO2");
```

**Comment by pgrawehr** [comment]
Since the GpioController is no longer sealed, adding a LibgpiodController could be an option. Adding public methods to the drivers should only be used if there's a very specific use case where the given methods are used (typically from within a single class). This approach should IMHO not be used for things that are possibly used accross an entire application.

**Comment by joperezr** [comment]
That's a good point @pgrawehr! I think perhaps the best way to go here would be to create a LibGpiodController that exposed those string overloads. If the list of pin names is static, we could even add an Enum so that it is strongly typed.

**Comment by joperezr** [comment]
@microhobby do you think you'll get a chance any time soon to try out the suggestions that @pgrawehr and I had above?

**Pull request closed without merging**
