### PR TITLE
Enable BinSkim scan in nightly validation

### PR DESCRIPTION
**Pull request by MilenaHristova**
Enabling BinSkim scan over build artifacts in [Validate-DotNet pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=827) and the .NET staging pipeline based on company requirements.

We are required to run SDL tools on official builds and implement automated bug filling for the tools output. Currently we are running SDL checks over the source code in the nightly builds and in the .NET staging pipeline, but to be compliant we need to also run BinSkim over the produced artifacts.

This PRs is enabling BinSkim checks in the nightly run of [Validate-DotNet pipeline](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%3FdefinitionId%3D827&data=05%7C01%7Capatsula%40microsoft.com%7Cf299e81d804d48e6c88008db73cfb359%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638231108144663200%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T4Pt4cQfNKPlP9c7zXUlkSSgSd7IA06iatPgAAUmb%2F8%3D&reserved=0).

More information is in the [Automate BinSkim runs over official builds issue](https://github.com/dotnet/arcade-services/issues/2647)  

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/iot/pull/2098)

### CODE REVIEW

**Comment by pgrawehr** [comment]
Do you have an example of how the result looks like? I'm just curious about what this new test does.

**Comment by MilenaHristova** [comment]
> Do you have an example of how the result looks like? I'm just curious about what this new test does.

This is an example work item that got created for `windowsdesktop` https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1848201/

**Comment by krwq** [comment]
@MilenaHristova non Microsoft employees don't have access to this repo and that's large part of our maintainers. Are results of this going to be publicly visible? If this is MS specific policy can this be added outside of the repo?

**Comment by MilenaHristova** [comment]
> @MilenaHristova non Microsoft employees don't have access to these issues and that's large part of our maintainers. Are results of this going to be publicly visible? If this is MS specific policy can this be added outside of the repo?

I am not aware of an other way to add this, bugs are filed automatically by the SDL tool. On the other hand, I couldn't find any validation runs for his repo, @mmitche do we need to run SDL on `dotnet/iot` ?

**Comment by mmitche** [comment]
@MilenaHristova Nope. This is a .NET Foundation project.

**Comment by MilenaHristova** [comment]
> @MilenaHristova Nope. This is a .NET Foundation project.

ok, thanks. I'll remove it from the list and close this.

**Pull request closed without merging**
