### PR TITLE
Give better wiring instructions for 1-wire devices.

### PR DESCRIPTION
**Pull request by Hello1024**
The provided diagram is wrong (10k resistor is in series with the data line, leading to the device not working).  I believe it was intended as a pullup (as recommended by the datasheet)

However, since the pi IO pins are not 5v tolerant, to do that we need to pull up to 3.3v.

To avoid confusion, we also power the sensor from 3.3v (the datasheet allows this).

This removes the incorrect wiring diagram.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/iot/pull/2258)

### CODE REVIEW

**Review by pgrawehr — COMMENTED** [review]
Good catch, but please delete the wrong schema image then.

**Comment by Ellerbach** [comment]
Note: I took the liberty to move forward this documentation PR by adjusting the graphic and the source file.

**Comment by Ellerbach** [comment]
@Hello1024 you will have to accept the agrement, so that we can merge your PR with my adjustments once the pipelines will be green.

**Comment by pgrawehr** [comment]
The drawing is still wrong. The resistor should be a pullup, but currently it is in-line with the data line.

**Comment by Ellerbach** [comment]
[Triage] @Hello1024 please accept the licence agreement so we can merge! Thanks a lot!

**Comment by Hello1024** [comment]
@dotnet-policy-service agree

**Review by pgrawehr — APPROVED** [review]

**Comment by pgrawehr** [comment]
@Hello1024 Thanks. Merged now.

**Pull request merged**
