### PR TITLE
Fix build: use new I2C APIs in recently merged project

### PR DESCRIPTION
**Pull request by krwq**
Seems https://github.com/dotnet/iot/pull/357 despite beeing green on CI (even build restarted today) actually broke the build

### CODE REVIEW

**Comment by krwq** [comment]
merging to make the build great again

**Comment by joperezr** [comment]
I believe this happened because CI of #357 was queued before merging the I2c changes, and we didn't re-run it after merging the I2c changes.

**Comment by krwq** [comment]
@joperezr, I think the PR was still on older changes and thus was green and the other changes were already merged. Are we merging PR branch into master before running PR or we run it directly on commit from PR?

**Comment by joperezr** [comment]
We merge, so this would only happen if CI started before we merged the I2c PR.

**Pull request merged**
