### PR TITLE
Simplify license header

### PR DESCRIPTION
**Pull request by richlander**
- We decided that a two line scheme is better.
- It is simply a simplification. It has no actual or intended legal meaning/change.
- Same as https://github.com/dotnet/runtime/pull/38793

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
I was now so used to the 3 lines :-) Great it's simplified!

**Comment by pgrawehr** [comment]
I guess the license header in each file has no legal impact anyway. Whoever uses the code must check the license details anyway. (If in doubt, not specifying a license would mean "no rights granted").

**Comment by krwq** [comment]
LGTM, @richlander why do we need license header at all? Isn't root LICENSE file enough?

**Review by joperezr — APPROVED** [review]
Thanks a bunch for doing this @richlander

**Pull request merged**
