### PR TITLE
Fix Sense HAT sample

### LINKED ISSUE #1248: SenseHat sample throws runtime exceptions related to formatting
I'm currently writing a quickstart that uses this sample, but it's currently broken due to formatting exceptions at runtime.

I've already fixed it locally, but the file the fix is in is getting renamed in https://github.com/dotnet/iot/pull/1243 so I'm going to wait until that's merged before I submit a PR so as not to create a merge issue.

### PR DESCRIPTION
**Pull request by CamSoper**
Fixes #1248 

The values from the device binding are already formatted, so formatting them as numbers was throwing an exception. This PR removes the extra formatting.

### CODE REVIEW

**Review by joperezr — APPROVED** [review]
Thanks for fixing @CamSoper!

**Comment by richlander** [comment]
What is the reason for removing the units, like `hPa`? Surely that wasn't throwing an exception?

**Comment by joperezr** [comment]
I assumed that it was because the formatted string already has them, but if not, I do agree we should add them back.

**Comment by CamSoper** [comment]
I'll be honest, I was being lazy because I didn't want to do any debugging. I've had a long week. 🤷🏻‍♂️

The specific problem was that at some point the binding was changed to return `Pressure` and `Altitude` objects instead of numerical values and the sample wasn't changed to match.

I've noticed similar problems in the BME280 sample. I'm guessing there was a breaking change in UnitsNet or something at some point?

Anyway, it's *actually* fixed the right way now. Sorry about that, mea culpa.

**Comment by richlander** [comment]
That looks good to me now. Thanks!

**Review by richlander — APPROVED** [review]

**Pull request merged**
