### PR TITLE
Categorized device listing

### PR DESCRIPTION
**Pull request by krwq**
Contributes to: https://github.com/dotnet/iot/issues/126
Contributes to: https://github.com/dotnet/iot/issues/63

This is a first pass on the categorized device listing. I've quickly added categories to all devices.

We need to figure out which categories do we want and which ones to display.

Please take a look at devices such as BNO055 (it's present in multiple categories)

### CODE REVIEW

**Comment by shaggygi** [comment]
Referencing [this issue](https://github.com/dotnet/iot/issues/63#issuecomment-455824649) since it is somewhat related.  Not sure if it helps.

**Comment by shaggygi** [comment]
I like the simplicity with the category.txt for tagging.  I'm wondering if the files should be in the [Digital Twin Definition Language](https://github.com/Azure/IoTPlugandPlay/tree/master/DTDL) format.

While this makes it a little more complicated to structure/read compared to just the category text name, it would allow for more information.  Future tooling/SDKs/APIs provided by [IoT Plug and Play](https://github.com/Azure/IoTPlugandPlay) would help improve this support.

In addition, it might be an introduction to help learn more about that modeling language for doing other advanced features.  For example, let's say I'm building a module that has a Beagle Bone Black connected to a few different binding types... like an I/O expander (via I2C), a motor driver (via PWM) and RTC (via SPI).  We could reference those respective DTDL files as a starting place, update the module's DTDL file with how the devices are connected (i.e. defined pins, comm ports, etc.).  And if I understand how DTDL works with Azure IoT, just upload the module's file to begin monitor the connected sensors.  **Disclaimer**: Yes, I know this is simplified 😄 

Another future goal is to offer code generation for bindings.  While I like having the flexibility to develop functionality around a binding's component (for specific registers and other datasheet stuff), DTDL might offer a way to produce boilerplate code based on the provided metadata.  This would hopefully keep some things standardized between the bindings (e.g. private fields, constructors, property names, disposing, etc.).

#418 is related to this topic.  If you think using DTDL is something worth investigating, I can try to provide some example DTDL files based on a few current bindings.  Thoughts?

**Comment by shaggygi** [comment]
Here's another data point related to structuring devices.  It includes some categories and drivers for components.

https://github.com/torvalds/linux/tree/master/drivers/iio

**Comment by joperezr** [comment]
This looks good except for two comments I have:

1. It would be great if we can move the flat list to some other file(Device-Index.md perhaps) or remove it entirely as I think the categorized list is good enough.
2. It would be great if in the list we expand families, so instead of having one entry for Bmx280, have one entry for Bme280 and one for Bmp280. Also related, can we do different categories on devices that belong to the same family of bindings?

It would be good if @richlander takes a look at this.

**Comment by krwq** [comment]
@shaggygi DTDL looks interesting and I think we should investigate it but I don't think I'll address it in this PR. For linux source code - unfortunatelly it's GPL so can't look at it.
Would be useful to create an issue about this after this PR is merged and you can share all the details you have over there.

@joperezr I'll not address 2. in this PR as I'd need to do more digging which I don't have cycles for and it possibly is already covered by @shaggygi's suggestion.

**Comment by krwq** [comment]
@joperezr seems like everything which can be quickly addressed already is, can we merge this?

**Pull request merged**
