### PR TITLE
Corrected wording

### PR DESCRIPTION
**Pull request by shaggygi**
Overlooked previously

### CODE REVIEW

**Comment by krwq** [comment]
@shaggygi wasn't previous version correct? Usually you use `an` when you can hear the vowel and SPI is pronounces as `ES`-`PEE`-`I`

**Comment by krwq** [comment]
Worst is that even wikipedia is not consistent:
https://en.wikipedia.org/wiki/Serial_Peripheral_Interface

> In-system programmable AVR controllers (including blank ones) can be programmed using **a SPI** interface.

> **An SPI** host adapter lets the user play the role of a master on **an SPI** bus directly from a PC.

**Comment by shaggygi** [comment]
Good point.  I guess it depends on how you say the word (or acronym).  I usually spell the letters when saying I2C ( I square C).  For SPI, I say the word (like Spy) instead of letters ( S P O).

Confusing language sometimes 🤕

**Comment by krwq** [comment]
anyway, at least we are consistent now :P

**Pull request merged**
