### PR TITLE
Added PwmController interface

### PR DESCRIPTION
**Pull request by shaggygi**
Added controller interface for PWM to enable future bindings to implement.

### CODE REVIEW

**Comment by joperezr** [comment]
Changes in general look good to me @shaggygi thanks for adding. I'll just hold off a bit before merging so that I can get a quick consensus from the review panel about this.

**Comment by shaggygi** [comment]
@joperezr Sounds good.  Hopefully approval/check-in is not too far off.  I'm working on updating the [Pca9685 binding](https://github.com/dotnet/iot/tree/master/src/devices/Pca9685) to implement while trying to learn more about PWM-related stuff.

**Comment by shaggygi** [comment]
@joperezr I know I'm overlooking something, but don't see the new IPwmController interface in build 0.1.0-prerelease.19281.2.

Is there something I'm missing to pull the latest version?  Again, it must be a brain toot!

**Comment by shaggygi** [comment]
@joperezr disregard.  got latest and appears to work now.  sorry for confusion.

**Pull request merged**
