### PR TITLE
Enable SA1204

### PR DESCRIPTION
**Pull request by krwq**
Fixes: https://github.com/dotnet/iot/issues/1381

* [x] SA1201 - Not convinced about it, seems more noisy than worth it, I didn't find the order super obvious
* [x] SA1203 - ok - already enabled
* [x] SA1204 - I found the code easier to read in most cases
* [x] SA1214 - ok - already enabled
* [x] SA1215 - enabled, no errors so assuming this was intuitively done correctly or it doesn't exist

cc: @pgrawehr

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/iot/pull/1444)

### CODE REVIEW

**Comment by pgrawehr** [comment]
I'm not convinced, especially when it comes to the method ordering. You normally have similar methods (be they static or not) close to each other (or private helper methods). This tears that appart.

**Comment by krwq** [comment]
@pgrawehr look at the diff, in most cases this enforced nicer field order so that static data is on top along with const. Only some of them were methods - in most of them the enforced order made sense as it grouped the static methods together. I think overall there is more benefit, only ocassionally it is a mild inconvenience. As a bonus I also found one method which should have been static and was not (it was in the middle of other static methods)

**Comment by Ellerbach** [comment]
I have to say I'm like @pgrawehr I'm not fully convinced. This doesn't bring much more clarity. It mixes a bit the logic. While I understand the logic, the static on the top is not always the best to read. Especially when the variables are declared after.

**Comment by pgrawehr** [comment]
Unfortunately, there's no way of enforcing the ordering only for the fields (where I too find the rule useful) but not for the methods.

**Review by Ellerbach — APPROVED** [review]

**Pull request merged**
