### PR TITLE
Fixing MPU9250 calibration issue and AK8963 detection

### PR DESCRIPTION
**Pull request by Ellerbach**
- Fixing calibration issue #1140 
- Fixing AK8963 detection #1241
  - Added specific explanation how to check the possible issue
  - Added example to create the proper AK8963 device
  - Adjusted constructor

### CODE REVIEW

**Comment by krwq** [comment]
@VincentvanWijnbergen @FM1973 can you try if this is fixing your issues?

@Ellerbach you got some merge conflict here

**Review by krwq — APPROVED** [review]
LGTM code-wise. Would be nice to have confirmation from issue authors it's fixing their issue (I assume you only got attached version of AK8963)

**Comment by Ellerbach** [comment]
> LGTM code-wise. Would be nice to have confirmation from issue authors it's fixing their issue (I assume you only got attached version of AK8963)

yea, there's been quite some commits those days :-) I think I fixed properly the issue. Also as I had the sensor (for once) with me, I was able to check the calibration and I think it worked fine. At least I'm far from the values that were displayed in the issue

**Comment by FM1973** [comment]
@krwq Sure, I will test it and let you know.
One question: I´m currently using the nuget packages. To test the changes, would it make sense to clone the repo and refenrence the iot-bindings from there?

**Comment by Ellerbach** [comment]
> One question: I´m currently using the nuget packages. To test the changes, would it make sense to clone the repo and refenrence the iot-bindings from there?

Yes, and checkout the PR branch. For this, you should first fork this repository into your GitHub. Click the Fork button on the top right.
And clone your forked repo locally. I'm sure you perfectly know how to do this :-)
Then, to clone a specific PR (in this case 1268), here are the 3 magic lines to run in the directory you just cloned

```shell
git remote add dotnet https://github.com/dotnet/iot.git
git fetch dotnet pull/1268/head:pull_1268
git checkout pull_1268
```

Then yes, reference your code to point on the code itself or just run the sample for Mpu9250 and let me know!

**Pull request merged**
