### PR TITLE
Update permissions of dotnet-install.sh

### PR DESCRIPTION
**Pull request by krwq**
Every time I locally build iot repo on linux some build script updates permissions of dotnet-install.sh and it shows that my repo is unclean. This submits that change permanently.

### CODE REVIEW

**Comment by krwq** [comment]
@joperezr merging this since it seems harmless

**Comment by joperezr** [comment]
Interesting, I'm not sure if this change will be persisted as everything under /eng/common gets overridden by the arcade updates.

**Comment by krwq** [comment]
@joperezr perhaps we should generate PRs on linux then? (or both)

**Comment by joperezr** [comment]
that won't make a difference, what I meant is that darc updates from arcade rewrites these files automatically and submit PRs for the changes, so I wonder if this change will remain, in any case, I don't think that would be an issue. If you see this happen again in the future after this fix we can investigate more.

**Pull request merged**
