### PR TITLE
Adding Xml Docs to the package

### PR DESCRIPTION
**Pull request by joperezr**
cc: @carlossanlop @ericstj 

This will add all of the the xml docs (that mostly @shaggygi have added 😄) into the package so that consumers will get auto-completion and descriptions shown in VS.

@carlossanlop I'm aware that this is not the official process and that by doing this we won't be getting the docs pushed to MSDN. This is just a temporary solution to get the experience in a better state for package consumers today, and will follow up with you to go through the official process.

### CODE REVIEW

**Comment by shaggygi** [comment]
@joperezr not sure if this messes with your work here, but I was going to update a few summaries in the GPIO files.  Nothing big, just a few parameter names.  Hope to do soon after we get passed the I2C/SPI work.

**Comment by joperezr** [comment]
shouldn't collide with this, as long as both the parameters and the docs are updated at the same time.

**Comment by carlossanlop** [comment]
@joperezr thank you for this.
@mairaw we need to get the IoT code to show up in MS Docs. It's my understanding that we have never sent you the DLLs for this repo so you can generate the xmls with mdoc. Correct? If that's the case, would you mind telling @joperezr what are the necessary steps to generate the MS Docs xmls for the first time?
Another question that I have is: Will this code live inside dotnet-api-docs or will it go to another repo?

**Comment by mairaw** [comment]
Correct. I've never received this. Would this be a completely separate product from our other targets? 
If it is and you have a NuGet package for this project with all the xml comments, you might just want to request to onboard this new project at https://aka.ms/publish-on-docs.
Then, for this SDK, the docs could be completely auto-generated from source.

**Comment by krwq** [comment]
@joperezr @carlossanlop @mairaw for System.Devices pacakge I understand the docs but for Iot.Device.Bindings should we even have docs yet?

Those APIs may change in the future (we are allowed to do breaking changes there), wouldn't that cause issues with docs?

**Comment by carlossanlop** [comment]
@krwq this change will only add IntelliSense next to our current APIs. This change won't add or affect any public documentation in MS Docs.
So if the APIs change in the future, we will have to remember to update the documentation as well, and generate the new IntelliSense files that will live next to the dlls.
We had this problem temporarily with System.Text.Json, where the documentation remained a bit behind while the APIs got refactored multiple times. As long as it all gets properly documented before release, we should be good.

**Comment by joperezr** [comment]
> Those APIs may change in the future (we are allowed to do breaking changes there), wouldn't that cause issues with docs?

Yeah I only plan to have the System.Device.Gpio docs in MS Docs. Iot.Device.Bindings docs won't be pushed to MS Docs.

**Comment by krwq** [comment]
I just want to clarify that we will treat XML docs as source of truth for IoT.Device.Bindings. AFAIK doc is it's own source of truth elsewere (since XML docs go out of date) - for that package we want reverse. cc: @mairaw

**Comment by mairaw** [comment]
There are two modes for .NET SDKs: source code is the source of truth or docs is the source of truth.

I believe that the main .NET API docs is the only case where docs is the source of truth because of many constraints: .NET is not a single product, we can't add /// comments to the entire source, etc.

For iot, you could generate the SDK based on the XML docs and every time you have a new release, the API docs would be completely regenerated based on that. This is what we do for other SDKs, such as Roslyn, ML.NET, ASP.NET Core, etc. There's also the possibility of filter out namespaces. So, you can say that you don't want to include docs for Iot.Device.Bindings in docs, but include System.Device.Gpio.

**Comment by mairaw** [comment]
Let me know if you need help getting that started BTW! And adding and removing APIs between releases is not a problem. You can choose which versions you want to display (e.g. always latest as Roslyn) and the reflection tool would add and remove APIs as needed.

**Comment by joperezr** [comment]
> Let me know if you need help getting that started BTW! And adding and removing APIs between releases is not a problem. You can choose which versions you want to display (e.g. always latest as Roslyn) and the reflection tool would add and remove APIs as needed.

Thanks a lot @mairaw I will ping you soon about this 😄

**Pull request merged**
