### PR TITLE
Fixing DHT22 temperature measurement not correct

### PR DESCRIPTION
**Pull request by Ellerbach**
- Fixing issue #984 by correcting the calculation for DHT22 temperature

### CODE REVIEW

**Comment by BramEsendam** [comment]
@joperezr When will this be released on NuGet?

**Comment by joperezr** [comment]
We will be shipping a preview package to NuGet in around 3 weeks, but in the meantime you could always just reference our daily build packages. The latest (as of now) package version of Iot.Device.Bindings (version [1.1.0-prerelease.20162.2](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Iot.Device.Bindings&protocolType=NuGet&version=1.1.0-prerelease.20162.2)) already has this fix available. In order to consume that version, simply add the following source to your NuGet.config (or add a new NuGet.config right next to your .csproj if you don't have one already)

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!-- Your other NuGet sources like nuget.org goes here -->
    <add key="dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Pull request merged**
