### PR TITLE
Update namespace from recent SPI/I2C changes

### PR DESCRIPTION
**Pull request by shaggygi**
Updated bindings to not reference the older Drivers namespace.

### CODE REVIEW

**Comment by krwq** [comment]
@joperezr I'm surprised this PR is green considering that https://github.com/dotnet/iot/pull/547 is not merged yet and this PR doesn't include that changes which actually change the namespace

**Comment by krwq** [comment]
@joperezr ahh it tries to merge into the PR branch - disregard

**Comment by shaggygi** [comment]
@krwq for understanding purposes... was this correct?  this merge was outside of my norm.

**Comment by krwq** [comment]
@shaggygi seems it didn't run CI at all here, see errors in the other PR

**Pull request merged**
