### PR TITLE
Re-iterate on devices conventions

### PR DESCRIPTION
**Pull request by krwq**
Fixes 3.0 part (docs update) of #419

cc: @joperezr @bartonjs 

@shaggygi please let me know what else should be clarified here (anything in this doc)

### CODE REVIEW

**Comment by shaggygi** [comment]
> Only the most useful APIs should be public, anything else which may be useful but will unlikely get used by most of the people should be protected (inheriting the class allows you to use it but it is not visible by default) or internal/private

Not part of this PR, but related topic.  This is a bit vague.  Not sure how we could keep consistent.  As stated previously, my opinion on binding APIs is they should be designed around the provided datasheet.  This allows for low-level interaction if users need.  You can then have the higher-level methods provided to perform the simpler calls (that most would use).  For example, `ReadDateTime` might be all that is needed for a RTC.  However, there might be some odd registers/bits that need to be changed to perform certain cases (daylight savings, alerts, exception flags, etc.).

It would be better to offer both scenarios within core binding class as I don't won't to be required to create a separate API that inherits just to offer a public enum/register property.  If I created a PR to add that additional API, there would be many back/forth discussions on why it is needed, etc.  For example, the MCP25xxx CAN device includes many registers to perform many functions related to the protocol.  With all the possible configurations, the API surface should allow to easily access the lower-level and then have higher-lever calls like `SendCanMessage`, etc.

Just my 2 pennies.

**Comment by krwq** [comment]
@shaggygi I think this should be covered here and this kind of stuff is what I meant by `what else should be clarified here`. Let's gather a list of questions you might think of and I'll talk with folks to figure out what the official stance is on that.

cc: @ZhangGaoxing @Ellerbach

**Comment by shaggygi** [comment]
@richlander was recently on an [episode of Azure DevOps Podcast](http://azuredevopspodcast.clear-measure.com/richard-lander-on-net-core-runtime-episode-50) and I believe this comment (around the 50 minute mark) fits my thinking.

When it comes to interfaces, you could have something like `ReadDateTime()` for a binding that implements an `IRealTimeClock`.  However, you could still expose the specifics of each device that implements that interface to allow users to get to specific features (registers, memory, etc.) of the device if they choose to.

**Comment by krwq** [comment]
@shaggygi let's not start the interface conversation in this PR :smile:

My initial thoughts on `everything` vs `only easy to use stuff` is following:
- whatever is easy to use should be public
- whatever is all/full functionality should be protected or be in a separate class (if there is easy to use class it's fine to also have full implementation separately but easy to use stuff must be in all of the samples first)

I haven't talked with other people about this yet but that was our initial thoughts when I did have some conversations months back

**Comment by joperezr** [comment]
I'm fine with both of the changes that you are making here since those we had already agreed upon. As to for the expose all APIs or just the most common stuff, I do agree with @shaggygi where I believe that exposing everything should be the goal in most cases, and only on some very special cases should we instead remove whatever is not necessary(These are just guidelines for most bindings, but we can have exceptions to the rules).

**Comment by krwq** [comment]
@joperezr I've heard exactly opposite opinions (make it as simple to use as possible) in the past so we will need to discuss this - there is value in having both.

**Comment by joperezr** [comment]
at least I believe we do all agree on the changes you are making on this PR, so let's go ahead and merge this and continue the discussion for other things in the already existing issue. That way we won't have stalled PRs for a long time till we come all to consensus.

**Comment by krwq** [comment]
@joperezr one more look please at the latest commit

**Comment by krwq** [comment]
@shaggygi please let me know if your concerns/questions are addressed here

**Pull request merged**
