### PR TITLE
Feed cleanup

### PR DESCRIPTION
**Pull request by mmitche**
Switch away from blob feeds

### CODE REVIEW

**Comment by JohnTortugo** [comment]
Ping. build failed.

**Comment by mmitche** [comment]
Thanks, I'll poke around at it a bit to figure out what the right feeds to add are, or which packages need to be pushed to other feeds.

**Comment by joperezr** [comment]
I know what it is, we depend on an old version of the compilers, which needs to be updated, I'll take care of this @mmitche

**Comment by mmitche** [comment]
> I know what it is, we depend on an old version of the compilers, which needs to be updated, I'll take care of this @mmitche

Sounds good, I can also push that version to the appropriate feed if it faisl.

**Comment by joperezr** [comment]
Thanks @mmitche

**Pull request merged**
