### PR TITLE
Fixes #1078: Add support for Sht1x sensors

### LINKED ISSUE #1078: SHT1x support
Currently there is support for the SHT3x sensors. However, there is no support for the older SHT1x sensors which are still widely available for purchase. I would like to add support for the SHT1x line of devices, either by modifying the existing SHT3x code or by using that code as a basis.

image

Datasheet: https://www.sparkfun.com/datasheets/Sensors/SHT1x_datasheet.pdf

### PR DESCRIPTION
**Pull request by frogcrush**
This is an in-progress PR to add support for Sht1x sensors. 

Still needs to be done:
- [ ] Add support for the heater element
- [ ] Add support for changing resolution
- [ ] Add support for changing the device registers
- [ ] Add dew point
- [ ] Fix style issues, etc.
- [ ] Test with device

### CODE REVIEW

**Comment by krwq** [comment]
@frogcrush do you think you'll have time to fix build errors? I'd recommend to change namespace to generalize family of device instead of matching it with type

**Comment by krwq** [comment]
@frogcrush let me know if you need any help with git

**Comment by frogcrush** [comment]
Yeahhh I screwed something up it seems

**Comment by krwq** [comment]
@frogcrush you can likely fix it if you locally do something along the lines (make sure to not have any uncommited changes):

```
git checkout -b fixedbranch master
git reset --hard b7a48f8
```

from there you should be at point before it's screwed up (you can skip first step of creating new branch if you feel confident)

after that I'd recommend to rebase next but only if you are sure you'll not have any merge conflicts.

If you do expect merge conflicts (if it's new folder you should not have any):
I'll recommend to squash all your changes into single commit first with:
`git rebase -i b8c0131c1ed50986faa1fe78024dc9e7225eb153` and leave only first commit and for the rest of them change them to squash;

`b8c0131c1ed50986faa1fe78024dc9e7225eb153` is one commit before you started making any changes on this branch. Not doing so you'll need to fix conflicts for each commit you made here separately.

Once you see merge conflicts I recommend to use some kind of merge tool and use it to fix it (`git mergetool` but you need to configure it first. I personally use Beyond Compare, some people use VS and are happy with it, to each their own; I'll not put instructions for that here). You can also do it by hand if it's not much (you'll see lots of `>>>` in the file with the conflicts and need to chose what's right). If you had merge conflicts you'll need to next call `git rebase --continue` after you're done fixing the commit.

To rebase (do `git remote -v` to see which of your remotes is `dotnet/iot`, i.e. I'll assume below it's called `dotnet`)

```
git rebase dotnet/master
```

 After that make sure everything still builds and make additional changes if needed. Later you'll need to re-open this PR and force push to frogcrush/master (force push because you want to overwrite bad changes)

Hope that helps.

**Comment by frogcrush** [comment]
Hey @krwq thanks for taking the time to write out these instructions. I think I've fixed my copy of the repo but I realized I made the changes, and this pull request, in my master branch which isn't very helpful when I am working on other device support at the same time. I will leave this PR closed and open a new one when ready with the Sht1x sensor unless that's a problem?

**Pull request closed without merging**
